<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>NINA.RetroKiwi.Plugin.SonyCamera</RootNamespace>
    <AssemblyName>NINA.RetroKiwi.Plugin.SonyCamera</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="ReachFramework" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NINA.Plugin" Version="3.2.0.3001-rc" />
    <PackageReference Include="System.ComponentModel.Composition" Version="8.0.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.6.0-preview3.19128.7" />
    <PackageReference Include="EntityFramework" Version="6.4.4" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="8.0.0" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Collections.Immutable" Version="8.0.0" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Accord" Version="3.8.2-alpha" />
    <PackageReference Include="Accord.Imaging" Version="3.8.2-alpha" />
    <PackageReference Include="Accord.Math" Version="3.8.2-alpha" />
    <PackageReference Include="Accord.Statistics" Version="3.8.2-alpha" />
    <PackageReference Include="AsyncEnumerator" Version="4.0.2" />
    <PackageReference Include="Castle.Core.AsyncInterceptor" Version="2.1.0" />
    <PackageReference Include="CommonServiceLocator" Version="2.0.7" />
    <PackageReference Include="CSharpFITS" Version="1.1.0" />
    <PackageReference Include="Dirkster.AvalonDock" Version="4.72.1" />
    <PackageReference Include="SHA3" Version="1.0.0" />
    <PackageReference Include="SharpGIS.NmeaParser" Version="2.2.2" />
    <PackageReference Include="System.Windows.Interactivity.WPF" Version="2.0.20525" />
    <PackageReference Include="ToggleSwitch" Version="1.2.0" />
    <PackageReference Include="VVVV.FreeImage" Version="3.15.1.1" />
    <PackageReference Include="Zlib.Portable.Signed" Version="1.11.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Tests\**\*.cs" />
    <Compile Remove="SonyCameraPluginNative\obj\Debug\.NETFramework,Version=v4.8.AssemblyAttributes.cs" />
    <Compile Remove="SonyCameraPluginNative\obj\Release\.NETFramework,Version=v4.8.AssemblyAttributes.cs" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.Settings</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <None Update="Properties\Settings.Settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
  <PropertyGroup />
  <Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition="'$(OS)' == 'Windows_NT'">
    <Exec Command="if not exist &quot;%25localappdata%25\NINA\Plugins\3.0.0&quot; (&#xA;  echo &quot;Creating $(PlatformName) Plugins folder&quot;&#xA;  mkdir &quot;%25localappdata%25\NINA\Plugins\3.0.0&quot;&#xA;)&#xA;if not exist &quot;%25localappdata%25\NINA\Plugins\3.0.0\$(TargetName)&quot; (&#xA;  echo &quot;Creating $(PlatformName) Plugins $(TargetName) folder&quot;&#xA;  mkdir &quot;%25localappdata%25\NINA\Plugins\3.0.0\$(TargetName)&quot;&#xA;)&#xA;&#xA;echo &quot;Copying $(PlatformName) $(TargetFileName)&quot;&#xA;xcopy &quot;$(TargetPath)&quot; &quot;%25localappdata%25\NINA\Plugins\3.0.0\$(TargetName)&quot; /h/i/c/k/e/r/y" />
  </Target>
</Project>
